title: Streamdata API Gallery - Iconfinder
description: A gallery of APIs to demonstrate what is possible when it comes to making data, content, and algorithms more real time, and event-driven as part of the API economy.
url: iconfinder.streamdata.gallery
tag: Iconfinder
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery-entities
github_repo: iconfinder
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
